# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Dl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AttributeF(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # AttributeF
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AttributeF
    def F(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateAttributeF(builder, f):
    builder.Prep(4, 4)
    builder.PrependFloat32(f)
    return builder.Offset()
